BASE:
  #log等级
  log_level: "debug"
  #扩展名
  log_extension: ".log"

  test:
    url: "http://127.0.0.1:9000/api"
    case_file: "api tc.xlsx"
    case_sheet: "Login"

Email:
  smtp_server: "smtp.163.com"
  smtp_port: 25
  email_from: "dachai1985@163.com"
  password: "Chj1985023"
  email_to: "dachai1985@163.com"